import { Globe } from "lucide-react";
import Image from "next/image";

/**
 * Presentational builder "screenshot" frame: browser chrome + media body.
 * No motion/scroll of its own — the Hero owns the scroll-linked transforms and
 * wraps this. The body image is generated by `pnpm screenshots`
 * (public/builder.jpeg).
 */
export function BuilderFrame() {
  return (
    <div className="relative overflow-hidden rounded-2xl border bg-background shadow-2xl shadow-indigo-500/10 ring-1 ring-black/5">
      {/* browser chrome */}
      <div className="flex h-10 items-center gap-2 border-b bg-muted/60 px-4">
        <span className="flex gap-1.5">
          <span className="size-2.5 rounded-full bg-red-400/80" />
          <span className="size-2.5 rounded-full bg-yellow-400/80" />
          <span className="size-2.5 rounded-full bg-green-400/80" />
        </span>
        <div className="mx-auto flex items-center gap-1.5 rounded-md border bg-background/70 pl-1.5 pr-3 py-1 text-[11px] text-muted-foreground">
          <Globe className="size-3" />
          https://resummme.asaa.dev/editor/canvas
        </div>
      </div>

      {/* media body */}
      <div className="relative aspect-video w-full bg-muted">
        <Image
          src="/builder.jpeg"
          alt="The Resummme editor"
          fill
          priority
          sizes="(max-width: 1024px) 100vw, 1024px"
          className="object-cover object-top"
          quality={100}
        />
      </div>
    </div>
  );
}
