import Image from "next/image";

import { Marquee } from "./marquee";
import { Reveal, RevealItem, RevealStagger } from "./reveal";

type TemplateMeta = {
  id: string;
  label: string;
  /** Screenshot generated by `pnpm screenshots` (public/templates/<id>.jpeg). */
  src: string;
};

const TEMPLATES_TOP: TemplateMeta[] = [
  { id: "classic", label: "Classic" },
  { id: "sidebar", label: "Sidebar" },
  { id: "modern-centered", label: "Modern" },
  { id: "timeline", label: "Timeline" },
  { id: "academic", label: "Academic" },
  { id: "minimal", label: "Minimal" },
  { id: "inset", label: "Inset" },
].map((t) => ({ ...t, src: `/templates/${t.id}.jpeg` }));

const TEMPLATES_BOTTOM: TemplateMeta[] = [
  { id: "classic-alt", label: "Classic" },
  { id: "sidebar-alt", label: "Sidebar" },
  { id: "modern-centered-alt", label: "Modern" },
  { id: "timeline-alt", label: "Timeline" },
  { id: "academic-alt", label: "Academic" },
  { id: "minimal-alt", label: "Minimal" },
  { id: "inset-alt", label: "Inset" },
].map((t) => ({ ...t, src: `/templates/${t.id}.jpeg` }));

function TemplateCard({ template }: { template: TemplateMeta }) {
  return (
    <div className="group relative aspect-[1/1.414] w-60 shrink-0 overflow-hidden rounded-xl border bg-background">
      <Image
        src={template.src}
        alt={`${template.label} resume template`}
        fill
        sizes="240px"
        className="object-cover object-top"
        loading="lazy"
      />
      {/* label revealed on hover */}
      <div className="absolute inset-x-0 bottom-0 flex items-end justify-center bg-linear-to-t from-black/65 via-black/20 to-transparent px-3 pt-10 pb-3 opacity-0 transition-opacity duration-300 group-hover:opacity-100">
        <span className="text-sm font-semibold text-white">
          {template.label}
        </span>
      </div>
    </div>
  );
}

export function TemplateCarousel() {
  const topCards = TEMPLATES_TOP.map((template) => (
    <TemplateCard key={template.id} template={template} />
  ));
  const bottomCards = TEMPLATES_BOTTOM.map((template) => (
    <TemplateCard key={template.id} template={template} />
  ));

  return (
    <section className="relative overflow-hidden py-24 sm:py-32">
      {/* soft purple glow so the section isn't flat white */}
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0"
        style={{
          background:
            "radial-gradient(1000px 560px at 50% 40%, rgba(139, 92, 246, 0.16), transparent 70%)",
        }}
      />

      {/* header */}
      <RevealStagger className="relative mx-auto max-w-2xl px-6 text-center">
        <RevealItem>
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Customize your{" "}
            <span className="bg-linear-to-r from-violet-500 to-indigo-600 bg-clip-text text-transparent">
              resume
            </span>
          </h2>
        </RevealItem>
        <RevealItem>
          <p className="mt-4 text-muted-foreground">
            Pick a template, tweak the colors and fonts, and make it
            unmistakably yours.
          </p>
        </RevealItem>
      </RevealStagger>

      {/* marquee rows, bounded to a wide max width and dissolving to white at the edges */}
      <Reveal className="relative mx-auto mt-14 max-w-[110rem]">
        <div className="flex flex-col gap-6">
          <Marquee direction="left" speed={28}>
            {topCards}
          </Marquee>
          <Marquee direction="right" speed={28}>
            {bottomCards}
          </Marquee>
        </div>

        <div className="pointer-events-none absolute inset-y-0 left-0 z-10 w-24 bg-linear-to-r from-background to-transparent sm:w-64" />
        <div className="pointer-events-none absolute inset-y-0 right-0 z-10 w-24 bg-linear-to-l from-background to-transparent sm:w-64" />
      </Reveal>
    </section>
  );
}
